# ==============================================================================
# LING48/CS72 Homework 1: Eliza-style Chatbot
# Kenneth Lai (kenneth.han.lai@dartmouth.edu)
# Last modification: 2024/01/03
#
# The program uses regular expressions to parse a user's input and generate a
# response in Spanish (or another language, if you choose). Be sure to test your
# regular expressions. I recommend making them in a site like
# https://regex101.com/. 
# ==============================================================================

# Import libraries for processing of operating system input (os, sys), 
# string handling (string), and regular expressions (re)
import os
import sys
import string
import re

# ==============================================================================
# Function:     eliza
#
# Input:        userInput (a string with a phrase in the Spanish language)
# Output:       reply (a string with a response, in Spanish, generated by the
#               function)
# Description:  The function uses regular expressions to read input from the
#               user and produce a response using natural language (Spanish).
#               Right now the function is just a template, so it can only
#               respond to the greeting 'Mi nombre es ...' (My name is ...).
# ==============================================================================

def eliza(userInput):

    # Create the variable output, which will contain our response
    output = ''

    # Create the regular expressions
    # You can test your regular expressions in numerous websites, such as
    # https://regex101.com/
    reHello1 = r'Mi nombre es (.*)'
    # reHello2 = ...
    # reHello3 = ...
    # ...

    groupHello1 = re.search(reHello1, userInput, re.IGNORECASE)
    # groupHello2 = re.search(reHello2, userInput, re.IGNORECASE)
    # groupHello3 = re.search(reHello3, userInput, re.IGNORECASE)
    # ...

    # if the input matches the regular expression:
    if groupHello1:
        # Then search for the relevant capturing group and extract it.
        # Then use it to construct the string 'Hola, CAPTUREGROUP. ¿Cómo estás?'
        # and put it in the output variable.
        output = 'Hola, ' + groupHello1.group(2) + '. ¿Cómo estás?'
    # If the input doesn't match the first regular expression, then keep trying
    # to match it to the other regular expressions we have.
    # elif groupHello2:
    #     ...
    # elif groupHello3:
    #     ...
    # ...
    # If the input does not match any of the regular expressions, then return
    # the generic reply.
    else:
        output = 'Cuéntame más.'
        
    return output

# ==============================================================================
# Main body of the program
# The system listens to the input argument from the
# command line and generates a response in Spanish.
# ==============================================================================

# Read the input from the command line.
# If there are fewer than 2 arguments (the python file name and the input
# phrase), then the program will tell you that there was an error.
if (len(sys.argv) < 2):
    input = ''
    print("\nERROR: You didn't provide an input phrase\n")
else:
    input  = os.path.join('',sys.argv[1])
    output = eliza(input)
    # Print the input and the output
    print('You:      ' + input)
    print('Computer: ' + output)
